services:
  postgres:
    image: "postgres:16.3"
    container_name: "postgres"
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5436:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data


  airflow-initdb:
    build: ./airflow
    depends_on:
      - postgres
    entrypoint: airflow db migrate && airflow connections create-default-connections


  airflow-webserver:
    build: ./airflow
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
    ports:
      - "8082:8080"
    env_file:
      - env.cfg
    entrypoint: airflow webserver

  airflow-scheduler:
    build: ./airflow
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
    env_file:
      - env.cfg
    entrypoint: airflow scheduler

  postgres-db:
    image: postgres:16-bookworm
    container_name: "postgres_db"
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    env_file:
      - env.cfg
    # environment:
    #   POSTGRES_DB: $POSTGRES_DB_DB
    #   POSTGRES_USER: $POSTGRES_USER_DB
    #   POSTGRES_PASSWORD: $POSTGRES_PASSWORD_DB
    #   PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - de15_lab08-data:/var/lib/postgresql/data
    ports:
      - "5438:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nplstudent -d de15_lab08"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

volumes:
  de15_lab08-data:


